<!-- modificators:
question--answered
question--answered question--answered-wrong
question--beeline //-->

<div class="question question--go">
</div>

<script type="text/template" id="question_popup_tmpl">
	<div class="question__top">
		<ul class="question__state">
			<li>1</li>
			<li>2</li>
			<li>3</li>
		</ul>

		<div class="question-author">
			<div class="question-author__img"><img  src="
			<% if (authorName == 'fromMorgan') { %>
				<?= publicdir("images/q/freeman.png")?>
				<% } else if (authorName == 'fromBeeline') {%>
				<?= publicdir("images/q/beeline.svg")?>
				<% } else if (authorName == 'fromNatgeo') {%>
				<?= publicdir("images/q/natgeo.svg")?>
				<% } %>
			"></div>
			<div class="question-author__info">
				<div class="question-author__name"><%= authorName %></div>
				<div class="question-author__points"><%= points + ' ' + pointUnits %></div>
			</div>
		</div>
	</div>

	<div class="question__body">
		<form>
			<div class="question__item">
				<div class="question__txt">
					<span class="yellow">ВОПРОС</span> <%= question %>
				</div>
				<div class="question__opts">
					<input type="radio" name="opt" id="option1" value="1"><label for="option1"><%= answers[0] %></label>
					<input type="radio" name="opt" id="option2" value="2"><label for="option2"><%= answers[1] %></label>
					<input type="radio" name="opt" id="option3" value="3"><label for="option3"><%= answers[2] %></label>
				</div>
			</div>
			<div class="question__add">

				<div class="question__before-answer visible">
					<div class="question__time"><span id="timer_val" class="question__time-sec-value">20</span><span class="question__time-sec-label" id="timer_label">секунд</span> времени</div>
					<button id="question_btn_answer" class="btn btn-sm question__submit visible" disabled>Ответить</button>
				</div>

				<div class="question__timeout-label">Время вышло</div>

				<div class="question__after-answer">
					<div class="question__var" id="question_result_ball"></div>
					<button id="question_btn_next" class="btn btn-sm question__submit visible">Следующий вопрос</button>
				</div>
				
			</div>
		</form>
	</div>
</script>
