<!-- modificators:
question--answered
question--answered question--answered-wrong
question--beeline //-->

<div class="question question--go">
</div>

<script type="text/template" id="question_popup_tmpl">
	<div class="question__img">
		<img  src="<?= publicdir("<%= pic %>")?>">
	</div>
	<div class="question__top">
		<ul class="question__state">
			<li>1</li>
			<li>2</li>
			<li>3</li>
		</ul>

		<div class="question-author">
			<div class="question-author__img"><img  src="<?= publicdir("<%= author_pic %>")?>"></div>
			<div class="question-author__info">
				<div class="question-author__name"><%= author_name %></div>
				<div class="question-author__points"><%= points %></div>
			</div>
		</div>
	</div>

	<div class="question__body">
		<form>
			<div class="question__item">
				<div class="question__txt">
					<span class="yellow">ВОПРОС</span> <%= question %>
				</div>
				<div class="question__opts">
					<input type="radio" name="opt" id="option1"><label for="option1"><%= answer1 %></label>
					<input type="radio" name="opt" id="option2"><label for="option2"><%= answer2 %></label>
					<input type="radio" name="opt" id="option3"><label for="option3"><%= answer3 %></label>
				</div>
			</div>
			<div class="question__add">
				<div class="question__time"><span>20</span>секунд времени</div>
				<button type="submit" href="#" class="btn btn-sm question__submit visible">Ответить</button>
				<!--
				<div class="question__var">0 баллов</div>
				<button type="submit" href="#" class="btn btn-sm question__submit visible">Следующий вопрос</button>
				-->
			</div>
		</form>
	</div>
</script>
