<!-- share -->
<div class="question question--share">
	<div class="question__img">
		<img  src="<?= publicdir("images/q/q1.jpg")?>">
		<div class="share-text">
			<div class="quote">
				Я побывал в Иерусалиме <br>вместе с Морганом Фриманом
			</div>
			<div class="share-text__sub">
				Морган Фриман. ИсториИ О БогЕ
			</div>
		</div>
	</div>
	<div class="question-sharings">
		<span class="question-sharings__head">рассказать друзьям</span>
		<ul class="social-list social-list--sharings">
			<li class="social-list__i">
				<a href="#" class="social-list__lk"><i class="icon icon-facebook"></i></a>
			</li>
			<li class="social-list__i">
				<a href="#" class="social-list__lk"><i class="icon icon-vkontakte"></i></a>
			</li>
			<li class="social-list__i">
				<a href="#" class="social-list__lk"><i class="icon icon-twitter"></i></a>
			</li>
		</ul>
	</div>
</div>
<!-- ./ share -->