<!-- share -->
<div class="question question--share"></div>
	<script type="text/template" id="share_popup_tmpl">
	<div class="question__img">
		<img src=<%= sharing.image %>>
		<div class="share-text">
			<div class="quote">
				<%= onCompleteText %>
			</div>
			<div class="share-text__sub">
				Морган Фриман. ИсториИ О БогЕ
			</div>
		</div>
	</div>
	<div class="question-sharings">
		<span class="question-sharings__head">рассказать друзьям</span>
		<div class="ya-share2" id="my-share" data-services="vkontakte,facebook,twitter"></div>

<!--		<ul class="social-list social-list--sharings">-->
<!--			<li class="social-list__i">-->
<!--				<a href="http://www.facebook.com/sharer.php?s=100&p[url]=<%= sharing.url %>&p[title]=<%= sharing.title %>&p[summary]=<%= sharing.description %>&p[images][0]=<%= sharing.image %>" onclick="window.open(this.href, this.title, 'toolbar=0, status=0, width=548, height=325'); return false" title="Поделиться ссылкой на Фейсбук" target="_parent"class="social-list__lk">-->
<!--					<i class="icon icon-facebook"></i></a>-->
<!--			</li>-->
<!--			<li class="social-list__i">-->
<!--				<a href="#" class="social-list__lk"><i class="icon icon-vkontakte"></i></a>-->
<!--			</li>-->
<!--			<li class="social-list__i">-->
<!--				<a href="#" class="social-list__lk"><i class="icon icon-twitter"></i></a>-->
<!--			</li>-->
<!--		</ul>-->
	</div>
</script>
<!-- ./ share -->