<div class="question question--start">
	<div class="question__img">
		<img  src="<?= publicdir("images/q/q1.jpg")?>">
	</div>
	<div class="question__top">
		<ul class="question__state">
			<li>1</li>
			<li>2</li>
			<li>3</li>
		</ul>
		<div class="question__tl">Вам нужно ответить на три вопроса</div>

	</div>
	<div class="question__body">
		<div class="question__var"><span>3</span>варианта ответа</div>
		<div class="question__time"><span class="question__time-sec-value">20</span>секунд времени</div>
	</div>
	<div class="btn-container-center">
		<a href="#" class="btn btn-sm" id="popup_btn_start">Начать</a>
	</div>
</div>
