<div class="container">
	<span class="footer__age">18+</span>
	<ul class="social-list">
		<li class="social-list__i">
			<a href="#" class="social-list__lk"><i class="icon icon-facebook"></i></a>
		</li>
		<li class="social-list__i">
			<a href="#" class="social-list__lk"><i class="icon icon-vkontakte"></i></a>
		</li>
		<li class="social-list__i">
			<a href="#" class="social-list__lk"><i class="icon icon-youtube"></i></a>
		</li>
	</ul>
	<ul class="sponsors-list">
		<li class="sponsors-list__i">
			<a href="#" class="sponsors-list__lk">
				<img src="<?= publicdir('images/beeline-logo.svg') ?>" class="sponsors-list__img sponsors-list__img--beeline">
			</a>
		</li>
	</ul>
</div>