<div class="container">
	<ul class="logo-list">
		<li class="logo-list__i">
			<a href="#" class="logo-list__lk"><img class="logo-list__img" src="<?= publicdir('images/header/logo-ng-channel.svg') ?>"></a>
		</li>
		<li class="logo-list__i">
			<a href="#" class="logo-list__lk"><img  class="logo-list__img logo-list__img--mag" src="<?= publicdir('images/header/logo-ng-magazine.svg') ?>"></a>
		</li>
	</ul>
	<button href="#" class="hamburger" id="toggle-menu">
		<span></span>
		<span></span>
		<span></span>
		<span></span>
	</button>
	<div class="menu-outer" id="nav">
		<?php include "nav.phtml" ?>
		<div class="user">
			<div class="user-enter">
				<span class="user-enter__head">Войти через соцсеть</span>
				<ul class="user-enter-lst">
					<li class="user-enter-lst__i fb"><a href="#popup-authorise" class="popup__caller" data-active=".fb"><i class="icon icon-facebook"></i></a></li>
					<li class="user-enter-lst__i vk"><a href="#popup-authorise" class="popup__caller" data-active=".vk"><i class="icon icon-vkontakte"></i></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
