<div class="nav">
	<ul class="menu">
		<li class="menu__i">
			<a href="#" class="menu__lk"><i class="icon icon-homepage"></i></a>
		</li>
		<li class="menu__i">
			<a href="#" class="menu__lk">О проекте</a>
		</li>
		<li class="menu__i">
			<a href="#" class="menu__lk">Правила</a>
		</li>
		<li class="menu__i">
			<a href="#" class="menu__lk">Рейтинг</a>
		</li>
		<li class="menu__i">
			<a href="#" class="menu__lk">Призы</a>
		</li>
	</ul>
</div>
