<div class="container">
<!--	<div class="video-container"></div>-->
	<div id="bgndVideo" class="player bg-player"
		 data-property="{videoURL:'https://youtu.be/mmf0KAHWlnk',containment:'.video-container', autoPlay:true, mute:true, startAt:0, showControls: false, opacity:1}">
	</div>
	<img class="about-logo" src="<?= publicdir('images/header/logo-ng-channel.svg') ?>">
	<div class="about-img-wrap">
		<img class="about-img" src="<?= publicdir('images/about-bg.1366.jpg') ?>">
		<img class="about-img about-img-sm" src="<?= publicdir('images/about-bg.768.jpg') ?>">
	</div>
	<div class="about">
		<div class="about__inn">
		<div class="about__caption">
			<div class="caption">
				<div class="caption__top">
					ИСТОРИИ О
				</div>
				<img class="caption__img" src="<?= publicdir('images/about-god.png') ?>" alt="Боге">
				<div class="caption__bottom">с<br>МОРГАНОМ<br>ФРИМАНОМ</div>
			</div>
		</div>
		<div class="about__body">
			<h1>О проекте</h1>
			<div class="about__col">
				<p>«Морган Фриман. Истории о Боге» — цикл познавательных передач на телеканале National Geographic. Вместе с ведущим зрители отправятся в захватывающее путешествие по культурным местам, знаковым событиям, научным исследованиям.</p>
				<p>Вместе с Морганом Фриманом мы отправляемся в увлекательное путешествие по миру в поисках ответов на вечные вопросы. Каждая серия будет рассказывать об одной важной проблеме, бесконечной и неизведанной тайне, которая влияет на жизни каждого человека, независимо от веры и религии.</p>
			</div>
			<div class="about__col">
				<p>Предложить зрителям совершить своё собственное виртуальное путешествие по знаковым местам, изучить и понять для себя природу непознанных явлений.</p>
				<p>Путешествуя, люди всегда стараются больше увидеть, разглядеть, получить новые эмоции. В нашем виртуальном туре мы также сделаем упор на визуальную составляющую проекта и дадим участникам пищу для размышлений. Тем более, что путешествовать пользователь будет не один, а в компании Моргана Фримана, Nat Geo и Билайн.</p>
			</div>
		</div>
		</div>
	</div>
</div>
