<div class="container">
	<section class="fullscreen-section flex-wrap" id="video-bg">
<!--		<div class="video-container"></div>-->
		<div id="bgndVideo" class="player bg-player"
			 data-property="{videoURL:'https://youtu.be/mmf0KAHWlnk',containment:'#video-bg', autoPlay:true, mute:true, startAt:0, showControls: false, opacity:1}">
		</div>
		<img class="about-logo" src="<?= publicdir('images/header/logo-ng-channel.svg') ?>">
		<div class="about-img-wrap">
			<img class="about-img" src="<?= publicdir('images/about-bg.1366.jpg') ?>">
			<img class="about-img about-img-sm" src="<?= publicdir('images/about-bg.768.jpg') ?>">
		</div>
		<div class="about">
			<div class="about__inn">
			<div class="about__caption">
				<div class="caption">
					<div class="caption__top">
						ИСТОРИИ О
					</div>
					<img class="caption__img" src="<?= publicdir('images/about-god.png') ?>" alt="Боге">
					<div class="caption__bottom">с<br>МОРГАНОМ<br>ФРИМАНОМ</div>
				</div>
			</div>
			<div class="about__body">
				<h1>О проекте</h1>
				<div class="about__col">
					<p>«Морган Фриман. Истории о Боге» — цикл познавательных передач на телеканале National Geographic. Вместе с ведущим зрители отправятся в захватывающее путешествие по культурным местам, знаковым событиям, научным исследованиям.</p>
					<p>Вместе с Морганом Фриманом мы отправляемся в увлекательное путешествие по миру в поисках ответов на вечные вопросы. Каждая серия будет рассказывать об одной важной проблеме, бесконечной и неизведанной тайне, которая влияет на жизни каждого человека, независимо от веры и религии.</p>
				</div>
				<div class="about__col">
					<p>Предложить зрителям совершить своё собственное виртуальное путешествие по знаковым местам, изучить и понять для себя природу непознанных явлений.</p>
					<p>Путешествуя, люди всегда стараются больше увидеть, разглядеть, получить новые эмоции. В нашем виртуальном туре мы также сделаем упор на визуальную составляющую проекта и дадим участникам пищу для размышлений. Тем более, что путешествовать пользователь будет не один, а в компании Моргана Фримана, Nat Geo и Билайн.</p>
				</div>
			</div>
			</div>
		</div>
	</section>
	<section class="fullscreen-section fullscreen-section--prize custom-height">
		<div class="fullscreen-container">
			<h1>Призы</h1>
			<h2>Главный приз - поездка на Камчатку</h2>
			<div class="prizes">
				<div class="prizes__i">
					<div class="prizes__tl">Свежий номер журнала National&nbsp;Geographic Россия</div>
					<div class="prizes__img"><img src="<?= publicdir('images/prizes/fresh-magazine.png') ?>"></div>
				</div>
				<div class="prizes__i prize-magazines">
					<div class="prizes__tl">Годовая подписка на&nbsp;журнал National&nbsp;Geographic Россия</div>
					<div class="prizes__img"><img src="<?= publicdir('images/prizes/magazines.png') ?>"></div>
				</div>
				<div class="prizes__i prize-beeline">
					<div class="prizes__tl">Годовая подписка<br>на&nbsp;Домашнее ТВ Билайн</div>
					<div class="prizes__img"><img src="<?= publicdir('images/beeline-logo.svg') ?>"></div>
				</div>
			</div>
		</div>
	</section>
	<section class="fullscreen-section fullscreen-section--partners custom-height">
		<div class="fullscreen-container">
			<h1>Партнеры</h1>
			<div class="partners">
				<div class="partners__col nat-geo">
					<div class="partners__img"><img src="<?= publicdir('images/header/logo-ng-magazine.svg') ?>"></div>
					<p>Журнал National Geographic — это официальный журнал Национального географического общества. Издается с 1888 года, мировая аудитория — более 38 млн. читателей! Публикуемые материалы — результат новаторских исследований, экспедиций, путешествий, археологических раскопок и т. д. В подготовке журнала принимают участие самые известные журналисты, фотографы,  путешественники и ученые. Только самые значимые результаты их работы попадают на страницы журнала.</p>
				</div>
				<div class="partners__col">
					<div class="partners__img"><img src="<?= publicdir('images/beeline-logo.svg') ?>"></div>
					<p>Услуги «Билайн» ежедневно обеспечивают надежную связь между людьми. Но мы уверены, что можем сделать больше. Современные технологии могут и должны помогать решению острых социальных проблем. Стратегия корпоративной социальной ответственности ПАО «ВымпелКом» определяет философию, основные принципы и критерии выбора проектов, реализуемых компанией на благо всех заинтересованных сторон — клиентов, сотрудников, акционеров, государства, общества в целом. ПАО «ВымпелКом» входит в группу компаний «ВымпелКом Лтд», которая является одним из крупнейших мировых интегрированных операторов связи, в который входят компании, предоставляющие услуги голосовой связи и передачи данных.</p>
				</div>
			</div>
		</div></section>
	<section class="fullscreen-section fullscreen-section--series custom-height">
		<div class="fullscreen-container">
			<h1>Серии</h1>
			<div class="episodes">
				<a href="#popup-video1" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode1.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
				<a href="#" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode2.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
				<a href="#" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode3.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
				<a href="#" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode4.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
				<a href="#" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode5.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
				<a href="#" class="popup__caller">
					<div class="episodes__i">
						<img class="episodes__img" src="<?= publicdir('images/episodes/episode6.jpg') ?>">
						<div class="episodes__text">
							<div class="episodes__tl">Тайна создания
								<span>4 апреля в 21:45 МСК</span>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
	</section>
</div>
<?php include "src/views/blocks/popup-video.phtml" ?>