<?php // example of including a block:
     // include "src/views/blocks/block-name.phtml" ?>

<section class="container">
<!--	<div class="video-container"></div>-->
	<div id="bgndVideo" class="player bg-player"
		 data-property="{videoURL:'https://youtu.be/mmf0KAHWlnk',containment:'.video-container', autoPlay:true, mute:true, startAt:0, showControls: false, opacity:1}">
	</div>
	<div class="watch">
		Смотри В <span class="yellow">«БиЛайн» ТВ <i class="link-icon"></i></span> National Geographic CHANNEL
	</div>
	<div class="caption">
		<div class="caption__top">
			ИСТОРИИ О
		</div>
		<img class="caption__img" src="<?= publicdir('images/about-god.png') ?>" alt="Боге">
		<div class="caption__bottom">с<br>МОРГАНОМ<br>ФРИМАНОМ</div>
	</div>
	<a href="#popup-reminder" class="btn popup__caller" id="popup-show">Напомнить о выходе первой серии</a>
</section>
