<div class="container">

<!--	<div id="bgndVideo" class="player bg-player"-->
<!--		 data-property="{videoURL:'https://youtu.be/mmf0KAHWlnk',containment:'.video-container', autoPlay:true, mute:true, startAt:0, showControls: false, opacity:1}">-->
<!--	</div>-->

	<aside class="map-aside">
		<h1>Выберите точку на карте</h1>
		<div class="btn-filter">
			<a href="#" class="btn">Все серии</a>
			<a href="#" class="btn">1 серия<span class="btn-date">4 апреля</span></a>
			<a href="#" class="btn">2 серия<span class="btn-date">11 апреля</span></a>
			<a href="#" class="btn inactive">3 серия<span class="btn-date">20 апреля</span></a>
			<a href="#" class="btn inactive">4 серия<span class="btn-date">24 апреля</span></a>
		</div>
	</aside>
	<main class="map-pointers">
		<a href="#q1" class="pointer" style="top: 200px; right:200px"><span>Иерусалим, Израиль</span></a>
		<a href="#q2" class="pointer" style="top: 320px; right:260px"><span>Иерусалим, Израиль</span></a>
	</main>
</div>
