<div class="container">
	<h1>Рейтинг</h1>
	<div class="rating">
		<div class="content-table">
		<div class="content-table__row hidden-mb">
			<div class="content-table__head">Место</div>
			<div class="content-table__head">Имя</div>
			<div class="content-table__head">Верные ответы</div>
			<div class="content-table__head">Баллы</div>
		</div>

		<div class="content-table__row on-top">
			<div class="content-table__cell">1</div>
			<div class="content-table__cell">
				<img src="<?= publicdir('/images/face.jpg') ?>">
				<span>Сергей Дудоров</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row on-top">
			<div class="content-table__cell">2</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Алексей Ростов</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row on-top">
			<div class="content-table__cell">3</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Женя Пшенин</span></div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">4</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Иванов Иван</span></div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">5</div>
			<div class="content-table__cell">
				<div class="content-table__img">

				</div>
				<span>Петрова Анна</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">6</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Иванов Иван</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">7</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Иванов Иван</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">8</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Петрова Анна</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">9</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Иванов Иван</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>
		<div class="content-table__row">
			<div class="content-table__cell">10</div>
			<div class="content-table__cell">
				<div class="content-table__img">
					<img src="<?= publicdir('/images/face.jpg') ?>">
				</div>
				<span>Иванов Иван</span>
			</div>

			<div class="content-table__cell"><span class="hidden-dt answers">Верных ответов</span><b>17/20</b> ср. время 18 сек.</div>
			<div class="content-table__cell"><span class="hidden-dt points">Баллов</span>30</div>

		</div>

	</div>
	</div>

	<?php include "src/views/blocks/paging.phtml" ?>

</div>