<footer class="paging">
	<span class="paging__lbl">В начало</span>
	<a href="#" class="paging__ctrl paging__ctrl--prev disabled"></a>
		<ul class="paging__list">
			<li class="paging__item active">1</li>
			<li class="paging__item"><a href="#">2</a></li>
			<li class="paging__item"><a href="#">3</a></li>
			<li class="paging__item"><a href="#">4</a></li>
			<li class="paging__divider">...</li>
			<li class="paging__item"><a href="#">12</a></li>
		</ul>
	<a href="#" class="paging__ctrl paging__ctrl--next"></a>
	<span class="paging__lbl">В конец</span>
</footer>