<div class="popup" id="popup-reminder">
	<a href="#" class="popup__closer" popup-closer>×</a>
	<div class="popup__body">
		<div class="reminder">
			<div class="h1">Напомнить о выходе ПЕРВОЙ СЕРИИ</div>
			<p>Сериал «Морган Фриман. Истории о Боге» стартует 4 апреля на телеканале National Geographic. Не пропустите ни одной серии этого поистине потрясающего зрелища! Подпишитесь на рассылку, и мы напомним вам о выходе серии заранее.</p>
			<form class="reminder-form" js-validate action="test.php" method="post" autocomplete="off">
				<button type="submit" class="reminder-form__submit">Отправить</button>
				<div class="reminder-form__group">
					<input class="reminder-form__ctrl" name="email" placeholder="e-mail" required data-rule-email="true" data-msg-required="Заполните поле" data-msg-email="Email введен с ошибкой">
				</div>
			</form>
		</div>
		<div class="done">
			<div class="h1">Спасибо</div>
			<p>Вы подписались на уведомление о выходе сериала «Морган Фриман. Истории о Боге». Уведомление будет отправлено на адрес <span id="done-email"></span></p>
		</div>
		<a href="#" class="btn" popup-closer>Закрыть</a>
	</div>
</div>