<div class="popup popup-authorise" id="popup-authorise">
	<a href="#" class="popup__closer" popup-closer>×</a>
	<div class="popup__body">
		<div class="user-enter">
			<div class="user-enter">
				<span class="user-enter__head">Войти через соцсеть</span>
				<ul class="user-enter-lst">
					<li class="user-enter-lst__i fb active"><a href="#"><i class="icon icon-facebook"></i></a></li>
					<li class="user-enter-lst__i vk"><a href="#"><i class="icon icon-vkontakte"></i></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>